# SPDX-License-Identifier: GPL-3.0-or-later
"""Localisation metadata for menu settings and the Kodi menu editor."""

SETTINGS_MESSAGES = {
    "menu_layout_help": (33600, "Set an item to 0 to hide it. Lower positive numbers appear first. Leave gaps between numbers so other items can be inserted later."),
    "flatten_monitoring_label": (33601, "Flatten Monitoring submenu"),
    "flatten_monitoring_help": (33602, "Show enabled Monitoring actions as one labelled block in the main menu instead of opening a submenu."),
    "flatten_queue_label": (33603, "Flatten Download queue submenu"),
    "flatten_queue_help": (33604, "Show enabled queue actions as one labelled block in the main menu instead of opening a submenu."),
    "flatten_retention_label": (33605, "Flatten Retention submenu"),
    "flatten_retention_help": (33606, "Show enabled retention actions as one labelled block in the main menu instead of opening a submenu."),
    "flatten_tools_label": (33607, "Flatten Tools & settings submenu"),
    "flatten_tools_help": (33608, "Show enabled setup and diagnostic actions as one labelled block in the main menu instead of opening a submenu."),
    "remote_editor_label": (33609, "TV-remote menu editor"),
    "remote_editor_help": (33610, "Batch-enable items, move an item directly to a destination, enter numeric positions, choose flattened groups, preview or restore the layout."),
    "preview_label": (33611, "Preview resolved menu"),
    "preview_help": (33612, "Show the exact current hierarchy, flattened labels, disabled entries and duplicate-position warnings."),
    "normalise_label": (33613, "Normalise positions"),
    "normalise_help": (33614, "Rewrite enabled items in every group as 10, 20, 30 and so on without enabling items set to 0."),
    "restore_label": (33615, "Restore menu defaults"),
    "restore_help": (33616, "Restore default positions, visibility and hierarchical submenus without changing service, retention or PIN settings."),
    "rank_item_heading": (33620, "Enter menu position — 0 hides this item"),
    "rank_group_heading": (33621, "Enter menu position — 0 hides this group"),
    "rank_submenu_heading": (33622, "Enter submenu position — 0 hides this item"),
    "preview_disabled_heading": (33630, "DISABLED"),
    "preview_warnings_heading": (33631, "WARNINGS"),
    "duplicate_rank_warning": (33632, "Duplicate {group} position {rank}: {actions}. Registry default and action ID break the tie."),
    "choose_group_heading": (33633, "Choose a menu group"),
    "visible_items_heading": (33634, "Visible {group} items"),
    "numeric_position_heading": (33635, "Set numeric position"),
    "numeric_input_heading": (33636, "{action} — enter 0 to hide"),
    "invalid_position": (33637, "Position must be a whole number from 0 to {maximum}."),
    "no_enabled_items": (33638, "This menu group has no enabled items."),
    "reorder_group_heading": (33639, "Reorder {group}"),
    "move_top": (33640, "Move to top"),
    "move_bottom": (33641, "Move to bottom"),
    "enter_numeric_position": (33642, "Enter numeric position"),
    "move_before": (33643, "Move before: {action}"),
    "move_after": (33644, "Move after: {action}"),
    "move_action_heading": (33645, "Move {action}"),
    "flatten_blocks_heading": (33646, "Flatten submenu blocks into the main menu"),
    "configure_menu_heading": (33647, "Configure menu"),
    "choose_visible_items": (33648, "Choose visible items"),
    "reorder_group_option": (33649, "Reorder {group}"),
    "choose_flattened_submenus": (33650, "Choose flattened submenus"),
    "save_exit": (33651, "Save and exit"),
    "preview_heading": (33652, "Menu layout preview"),
    "positions_normalised": (33653, "Menu positions normalised to 10, 20, 30, …"),
    "restore_confirm": (33654, "Restore default positions, visibility and submenu layout?"),
    "defaults_restored": (33655, "Default menu visibility and ordering restored."),
    "invalid_persisted_position": (33656, "Invalid position for {action}; using {default}."),
}

ACTION_HELP_IDS = {
    "request_search": 33700,
    "status": 33701,
    "search_now": 33702,
    "interactive_search": 33703,
    "monitoring": 33704,
    "queue": 33705,
    "dashboard": 33706,
    "find_subtitles": 33707,
    "retention": 33708,
    "delete_exclude": 33709,
    "delete_replace": 33710,
    "tools": 33711,
    "monitor": 33712,
    "unmonitor": 33713,
    "change_quality_profile": 33714,
    "queue_view": 33715,
    "queue_remove": 33716,
    "retention_preview": 33717,
    "retention_cleanup": 33718,
    "retention_report": 33719,
    "open_settings": 33720,
    "configure_request_defaults": 33721,
    "configure_subtitle_languages": 33722,
    "test_radarr": 33723,
    "test_sonarr": 33724,
    "test_backend": 33725,
    "test_prowlarr": 33726,
    "test_bazarr": 33727,
    "diagnostics": 33728,
    "configure_menu": 33729,
    "manage_pin": 33730,
    "retention_enable_periodic": 33731,
    "retention_disable_periodic": 33732,
}
