# SPDX-License-Identifier: GPL-3.0-or-later

ACTION_REGISTRY = [
    {
        "id": "status",
        "label_id": 32003,
        "default_label": "Status",
        "group": "root",
        "mode": "status",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": True,
        "advanced_mode": True,
        "default_order": 10,
    },
    {
        "id": "search_now",
        "label_id": 32004,
        "default_label": "Search & download now",
        "group": "root",
        "mode": "search_now",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": True,
        "advanced_mode": True,
        "default_order": 20,
    },
    {
        "id": "monitoring",
        "label_id": 32005,
        "default_label": "Monitoring",
        "group": "root",
        "mode": "monitoring_menu",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 30,
        "is_submenu": True,
    },
    {
        "id": "monitor",
        "label_id": 32006,
        "default_label": "Monitor",
        "group": "monitoring",
        "mode": "monitor",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 31,
    },
    {
        "id": "unmonitor",
        "label_id": 32007,
        "default_label": "Unmonitor",
        "group": "monitoring",
        "mode": "unmonitor",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 32,
    },
    {
        "id": "change_quality_profile",
        "label_id": 32008,
        "default_label": "Change quality profile",
        "group": "monitoring",
        "mode": "change_quality_profile",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 33,
    },
    {
        "id": "queue",
        "label_id": 32009,
        "default_label": "Download queue",
        "group": "root",
        "mode": "queue_menu",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 40,
        "is_submenu": True,
    },
    {
        "id": "queue_view",
        "label_id": 32010,
        "default_label": "View status",
        "group": "queue",
        "mode": "queue_view",
        "destructive": False,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 41,
    },
    {
        "id": "queue_remove",
        "label_id": 32011,
        "default_label": "Remove from queue",
        "group": "queue",
        "mode": "queue_remove",
        "destructive": True,
        "requires_selection": True,
        "simple_mode": False,
        "advanced_mode": True,
        "default_order": 42,
    },
    {
        "id": "delete_exclude",
        "label_id": 32001,
        "default_label": "Delete & Exclude",
        "group": "root",
        "mode": "delete_exclude",
        "destructive": True,
        "requires_selection": True,
        "simple_mode": True,
        "advanced_mode": True,
        "default_order": 50,
    },
    {
        "id": "delete_replace",
        "label_id": 32002,
        "default_label": "Delete & Replace",
        "group": "root",
        "mode": "delete_replace",
        "destructive": True,
        "requires_selection": True,
        "simple_mode": True,
        "advanced_mode": True,
        "default_order": 60,
    },
    {
        "id": "tools",
        "label_id": 32500,
        "default_label": "Tools & settings",
        "group": "root",
        "mode": "tools_menu",
        "destructive": False,
        "requires_selection": False,
        "simple_mode": True,
        "advanced_mode": True,
        "default_order": 70,
        "is_submenu": True,
    }
]

def get_action_by_id(action_id):
    for action in ACTION_REGISTRY:
        if action["id"] == action_id:
            return action
    return None

def get_action_by_mode(mode):
    for action in ACTION_REGISTRY:
        if action["mode"] == mode:
            return action
    return None
